"""add is_response_seen to contact_requests

Revision ID: 726c36b0ad9c
Revises: a84c218ccb7c
Create Date: 2026-05-14 14:15:33.295865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726c36b0ad9c'
down_revision: Union[str, Sequence[str], None] = 'a84c218ccb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_requests', sa.Column('is_response_seen', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_requests', 'is_response_seen')
    # ### end Alembic commands ###
