"""add storage locations, contact requests, audit logs, and superadmin

Revision ID: 80e12ff3ae93
Revises: 706e0b9c1926
Create Date: 2026-05-02 18:23:12.499272

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80e12ff3ae93"
down_revision: Union[str, Sequence[str], None] = "706e0b9c1926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE user_role_enum ADD VALUE IF NOT EXISTS 'SUPERADMIN'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "location_point",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index(
    #     "idx_storage_locations_location_point",
    #     "storage_locations",
    #     ["location_point"],
    #     unique=False,
    #     postgresql_using="gist",
    # )
    op.create_index(
        op.f("ix_storage_locations_name"), "storage_locations", ["name"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "entity_type",
            sa.Enum(
                "USER",
                "ADMIN",
                "CATEGORY",
                "LOST_REPORT",
                "FOUND_REPORT",
                "STORAGE_LOCATION",
                "CONTACT_REQUEST",
                name="entity_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                "STATUS_CHANGE",
                "HANDOVER",
                name="action_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False
    )
    op.create_table(
        "contact_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CANCELED",
                name="request_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_requests_report_id"),
        "contact_requests",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_requests_requester_id"),
        "contact_requests",
        ["requester_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_requests_target_user_id"),
        "contact_requests",
        ["target_user_id"],
        unique=False,
    )
    op.add_column(
        "found_reports", sa.Column("storage_location_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None, "found_reports", "storage_locations", ["storage_location_id"], ["id"]
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_constraint(None, "found_reports", type_="foreignkey")
    op.drop_column("found_reports", "storage_location_id")
    op.drop_index(
        op.f("ix_contact_requests_target_user_id"), table_name="contact_requests"
    )
    op.drop_index(
        op.f("ix_contact_requests_requester_id"), table_name="contact_requests"
    )
    op.drop_index(op.f("ix_contact_requests_report_id"), table_name="contact_requests")
    op.drop_table("contact_requests")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_storage_locations_name"), table_name="storage_locations")
    # op.drop_index(
    #     "idx_storage_locations_location_point",
    #     table_name="storage_locations",
    #     postgresql_using="gist",
    # )
    op.drop_table("storage_locations")
    # ### end Alembic commands ###
