"""add_response_message_to_contact_requests

Revision ID: a84c218ccb7c
Revises: 444b2c8ec159
Create Date: 2026-05-11 09:17:29.017843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'a84c218ccb7c'
down_revision: Union[str, Sequence[str], None] = '444b2c8ec159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_requests', sa.Column('response_message', Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_requests', 'response_message')
    # ### end Alembic commands ###
